openapi: 3.1.0
info:
  title: greet.v1
servers:
  - url: http://localhost:8081
    description: Local development server
paths:
  /v1/greet:
    post:
      tags:
        - greet.v1.GreetService
      summary: Greet
      description: Unary
      operationId: greet.v1.GreetService.Greet
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/greet.v1.GreetRequest"
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/connect.error"
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/greet.v1.GreetResponse"
components:
  schemas:
    greet.v1.GreetRequest:
      type: object
      properties:
        greeting:
          allOf:
            - title: greeting
            - $ref: "#/components/schemas/greet.v1.Greeting"
      title: GreetRequest
      additionalProperties: false
    greet.v1.GreetResponse:
      type: object
      properties:
        result:
          type: string
          title: result
      title: GreetResponse
      additionalProperties: false
    greet.v1.Greeting:
      type: object
      properties:
        firstName:
          type: string
          title: first_name
        lastName:
          type: string
          title: last_name
      title: Greeting
      additionalProperties: false
    connect-protocol-version:
      type: number
      title: Connect-Protocol-Version
      enum:
        - 1
      description: Define the version of the Connect protocol
      const: 1
    connect-timeout-header:
      type: number
      title: Connect-Timeout-Ms
      description: Define the timeout, in ms
    connect.error:
      type: object
      properties:
        code:
          type: string
          examples:
            - CodeNotFound
          enum:
            - CodeCanceled
            - CodeUnknown
            - CodeInvalidArgument
            - CodeDeadlineExceeded
            - CodeNotFound
            - CodeAlreadyExists
            - CodePermissionDenied
            - CodeResourceExhausted
            - CodeFailedPrecondition
            - CodeAborted
            - CodeOutOfRange
            - CodeInternal
            - CodeUnavailable
            - CodeDataLoss
            - CodeUnauthenticated
          description: The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
        message:
          type: string
          description: A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
        detail:
          $ref: "#/components/schemas/google.protobuf.Any"
      title: Connect Error
      additionalProperties: true
      description: "Error type returned by Connect: https://connectrpc.com/docs/go/errors/#http-representation"
    google.protobuf.Any:
      type: object
      properties:
        type:
          type: string
        value:
          type: string
          format: binary
        debug:
          type: object
          additionalProperties: true
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
security: []
tags:
  - name: greet.v1.GreetService
